### ISSUE TITLE
The efficiency concern of pure python loop

### ISSUE THREAD

**Issue by kanglcn** [isce-framework/spurt#39]
Dear spurt developers,

Thanks for make this advanced phase unwrapping package public!

I did a speed test with one big interferogram (30 million points) phase unwrapping using the `DelaunayGraph` and `ORMCFSolver`. Building the graph and unwrap one interferogram takes more than one hour. However, after more detailed testing I found calling the mcf solver from or-tools (which I think should be the most computational extensive part) takes only 3.5 minutes. The other codes, e.g., building the graph and flood filling, takes the majority of the time. I checked the source code and found many pure python loop and inefficient data structure usage like list and dict which I think may be the reason for the slowness.

I want to ask if you have any plan to accelerate this part? Probably using numba is a good choice.

Thanks you again for making this package. Please correct me if I am wrong.

**Comment by piyushrpt** [comment]
There is no plan to accelerate this part of the processing. We currently have no use cases where we plan to solve 30 million points as a single graph.
